// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pxdiervkbxtuzghpghry.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4ZGllcnZrYnh0dXpnaHBnaHJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNDEzMTQsImV4cCI6MjA1OTkxNzMxNH0.fUH-55rykG_YBKxiMDnbEvCNLjt5sIGRO4l_UlMKlTE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);